/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab1;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n1_tf = new javax.swing.JTextField();
        n2_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CongBtn = new javax.swing.JButton();
        TruBtn = new javax.swing.JButton();
        NhanBtn = new javax.swing.JButton();
        ChiaBtn = new javax.swing.JButton();
        result_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hoàng Nguyên - TS01667");

        jLabel1.setText("Num 1:");

        jLabel2.setText("Num 2:");

        CongBtn.setText("+");
        CongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CongBtnActionPerformed(evt);
            }
        });

        TruBtn.setText("-");
        TruBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruBtnActionPerformed(evt);
            }
        });

        NhanBtn.setText("*");
        NhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBtnActionPerformed(evt);
            }
        });

        ChiaBtn.setText("/");
        ChiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiaBtnActionPerformed(evt);
            }
        });

        result_tf.setEditable(false);
        result_tf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        result_tf.setFocusable(false);
        result_tf.setHighlighter(null);
        result_tf.setRequestFocusEnabled(false);
        result_tf.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        result_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_tfActionPerformed(evt);
            }
        });

        jLabel3.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CongBtn)
                        .addGap(18, 18, 18)
                        .addComponent(TruBtn)
                        .addGap(18, 18, 18)
                        .addComponent(NhanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ChiaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n1_tf)
                            .addComponent(n2_tf)
                            .addComponent(result_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n2_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CongBtn)
                    .addComponent(TruBtn)
                    .addComponent(NhanBtn)
                    .addComponent(ChiaBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CongBtnActionPerformed
        addTextToResultBox(n1_tf, n2_tf, '+');
    }//GEN-LAST:event_CongBtnActionPerformed

    private void NhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBtnActionPerformed
        addTextToResultBox(n1_tf, n2_tf, '*');
    }//GEN-LAST:event_NhanBtnActionPerformed

    private void TruBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruBtnActionPerformed
        addTextToResultBox(n1_tf, n2_tf, '-');
    }//GEN-LAST:event_TruBtnActionPerformed

    private void ChiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiaBtnActionPerformed
        addTextToResultBox(n1_tf, n2_tf, '/');
    }//GEN-LAST:event_ChiaBtnActionPerformed

    private void result_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_tfActionPerformed
    
    private void addTextToResultBox(JTextField field1, JTextField field2, char character) {
        try {
            if (field1.getText().isBlank()){
                JOptionPane.showMessageDialog(this,
                        "Vui lòng nhập dữ liệu 1");
                return;
            }
            if (field2.getText().isBlank()) {
                JOptionPane.showMessageDialog(this,
                        "Vui lòng nhập dữ liệu 2");
                return;
            }

            int n1 = Integer.parseInt(field1.getText());
            int n2 = Integer.parseInt(field2.getText());

            switch (character) {
                case '+': result_tf.setText(String.valueOf(n1+n2));
                    break;
                case '-': result_tf.setText(String.valueOf(n1-n2));
                    break;
                case '*': result_tf.setText(String.valueOf(n1*n2));
                    break;
                case '/': result_tf.setText(String.valueOf(n1/n2));
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập dữ liệu đầu vào là số");
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChiaBtn;
    private javax.swing.JButton CongBtn;
    private javax.swing.JButton NhanBtn;
    private javax.swing.JButton TruBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField n1_tf;
    private javax.swing.JTextField n2_tf;
    private javax.swing.JTextField result_tf;
    // End of variables declaration//GEN-END:variables
}
