/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab2;

import Extension.Actions;

import java.awt.*;
import java.util.*;
import java.util.List;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.table.*;

/**
 *
 * @author Admin
 */
public class Bai1 extends javax.swing.JFrame {
    public Bai1() {
        initComponents();
        Helper.fillToTable(students, tableBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        fullnameInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gradeInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Rank = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBox = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        rewardCheck = new javax.swing.JCheckBox();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        sortOnMark = new javax.swing.JButton();
        sortOnName = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ HỌC VIÊN");

        jLabel1.setText("HỌ VÀ TÊN");

        jLabel2.setText("ĐIỂM");

        course.setText("Lập trình Java 02");
        course.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("KHÓA HỌC");

        Rank.setForeground(new java.awt.Color(255, 255, 255));
        Rank.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Rank.setEnabled(false);

        jLabel4.setText("XẾP LOẠI");

        tableBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "KHÓA HỌC", "XẾP LOẠI", "THƯỞNG"
            }
        ));
        tableBox.setInheritsPopupMenu(true);
        tableBox.setPreferredSize(new java.awt.Dimension(100, 80));
        tableBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBoxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBox);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("QUẢN LÝ HỌC VIÊN");

        rewardCheck.setText("Có phần thưởng?");
        rewardCheck.setEnabled(false);

        updateBtn.setText("CẬP NHẬT");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addBtn.setText("THÊM");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        createBtn.setText("NHẬP MỚI");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("XÓA");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        sortOnMark.setText("Sắp xếp theo điểm");
        sortOnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortOnMarkActionPerformed(evt);
            }
        });

        sortOnName.setText("Sắp xếp theo tên");
        sortOnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortOnNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gradeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rewardCheck)
                                    .addComponent(Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updateBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(createBtn))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(sortOnMark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortOnName)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnameInput)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeInput)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rank)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(rewardCheck)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(addBtn)
                    .addComponent(createBtn)
                    .addComponent(deleteBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortOnMark)
                    .addComponent(sortOnName))
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // actions
    private void sortOnMarkActionPerformed(java.awt.event.ActionEvent evt) {
        students.sort(new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return (o1.getMarks() < o2.getMarks()) ? -1 : 1;
            }
        });
        Helper.fillToTable(students, tableBox);
    }

    private void sortOnNameActionPerformed(java.awt.event.ActionEvent evt) {
        students.sort((o1, o2) -> o1.getName().compareTo(o2.getName()));
        Helper.fillToTable(students, tableBox);
    }                                          

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (tableBox.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Bạn chưa chọn đối tượng để thay đổi");
            return;
        }

        Student st = students.get(tableBox.getSelectedRow());
        try{
            st.UpdateInfo(fullnameInput, gradeInput, course);
            Helper.fillToTable(students, tableBox);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this,
                    "Vui long click vào dữ liệu muốn sửa");
        }
    }

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Actions.resetTextField(fullnameInput, gradeInput, Rank);
        rewardCheck.setSelected(false);
    }

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (tableBox.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Bạn chưa chọn đối tượng để xóa");
            return;
        }

        students.remove(tableBox.getSelectedRow());
        Helper.fillToTable(students, tableBox);

        // Set về default
        Actions.resetTextField(fullnameInput, gradeInput, Rank);
        rewardCheck.setSelected(false);
    }

    private void tableBoxMouseClicked(java.awt.event.MouseEvent evt) {
        Student st = students.get(tableBox.getSelectedRow());
        Helper.showDetail(fullnameInput, gradeInput, course, Rank, rewardCheck, st);
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (fullnameInput.getText().isBlank() || gradeInput.getText().isBlank()
                || course.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ dữ liệu...");
            return;
        }
        
        try {
            double mark = Double.parseDouble(gradeInput.getText());
            if (!(mark >= 0 && mark <= 10)) {
                JOptionPane.showMessageDialog(this, "Hãy nhập điểm đúng cú pháp.");
                return;
            }
            students.add(new Student(
                fullnameInput.getText(), mark, course.getText()));
            Helper.fillToTable(students, tableBox);
            Actions.resetTextField(fullnameInput, gradeInput, Rank);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hãy nhập điểm đúng cú pháp.");
        }
    }

    static List<Student> students = new ArrayList<>(
        Arrays.asList(
            new Student[] {
                new Student("Hoàng Nguyên", 8.9, "Lập trình HTML/CSS"),
                new Student("Phương Nguyên", 7.9, "Maketing"),
                new Student("Khắc Nguyên", 8, "Công nghệ sinh học"),
                new Student("Thái Nguyên", 9, "Công nghệ Oto")
            })
    );
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rank;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField course;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fullnameInput;
    private javax.swing.JTextField gradeInput;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox rewardCheck;
    private javax.swing.JButton sortOnMark;
    private javax.swing.JButton sortOnName;
    private javax.swing.JTable tableBox;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
