/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab3;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.*;
import java.util.Base64;

/**
 *
 * @author Admin
 */
public class Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorGroup = new javax.swing.ButtonGroup();
        toolbarGroupbtn = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        exitAPp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPreview = new javax.swing.JTextArea();
        footerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        New_file = new javax.swing.JMenuItem();
        Open_file = new javax.swing.JMenuItem();
        Save_File = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        RedChoose = new javax.swing.JRadioButtonMenuItem();
        GreenChoose = new javax.swing.JRadioButtonMenuItem();
        BlueChoose = new javax.swing.JRadioButtonMenuItem();
        ColorChooser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        exitAppBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Java - Nguyên");

        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Icon\\Person.png")); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        aboutBtn.setIcon(new javax.swing.ImageIcon("D:\\Icon\\about.png")); // NOI18N
        aboutBtn.setFocusable(false);
        aboutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aboutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(aboutBtn);
        jToolBar1.add(jSeparator1);

        exitAPp.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        exitAPp.setIcon(new javax.swing.ImageIcon("D:\\Icon\\exit_to_app.png")); // NOI18N
        exitAPp.setFocusable(false);
        exitAPp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitAPp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitAPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(exitAPp);

        TextPreview.setColumns(20);
        TextPreview.setRows(5);
        TextPreview.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextPreviewKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TextPreview);

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FPOLY - JAVA 02");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        New_file.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        New_file.setText("New");
        New_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_fileActionPerformed(evt);
            }
        });
        jMenu1.add(New_file);

        Open_file.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Open_file.setText("Open");
        Open_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_fileActionPerformed(evt);
            }
        });
        jMenu1.add(Open_file);

        Save_File.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Save_File.setText("Save");
        Save_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_FileActionPerformed(evt);
            }
        });
        jMenu1.add(Save_File);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        colorGroup.add(RedChoose);
        RedChoose.setText("Red");
        RedChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedChooseActionPerformed(evt);
            }
        });
        jMenu2.add(RedChoose);

        colorGroup.add(GreenChoose);
        GreenChoose.setText("Green");
        GreenChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenChooseActionPerformed(evt);
            }
        });
        jMenu2.add(GreenChoose);

        colorGroup.add(BlueChoose);
        BlueChoose.setText("Blue");
        BlueChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueChooseActionPerformed(evt);
            }
        });
        jMenu2.add(BlueChoose);

        ColorChooser.setText("Text Color");
        ColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorChooserActionPerformed(evt);
            }
        });
        jMenu2.add(ColorChooser);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("System");

        jMenuItem2.setText("About us");
        jMenu3.add(jMenuItem2);

        exitAppBtn.setText("Exit");
        exitAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppBtnActionPerformed(evt);
            }
        });
        jMenu3.add(exitAppBtn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(footerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String filepath = "";
    Boolean isUpdateFile = false;
    JFileChooser fileChooser = new JFileChooser();

    private void New_fileActionPerformed(java.awt.event.ActionEvent evt) {                                         
        TextPreview.setText("");
        filepath = "";
        isUpdateFile = false;
    }                                       

    private void Open_fileActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_Open_fileActionPerformed
        fileChooser.setFileFilter(new FileNameExtensionFilter(
                "Chỉ chọn file có đuôi (*.dat)", "dat"));

        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            filepath = fileChooser.getSelectedFile().getAbsolutePath();
            try (FileInputStream fip = new FileInputStream(filepath)) {
                String dataTextFile = new String(fip.readAllBytes(), "UTF-8");
                TextPreview.setText(decodeBase64(dataTextFile));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_Open_fileActionPerformed

    private void Save_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_FileActionPerformed
        if (!filepath.isEmpty() && isUpdateFile) {
            try {
                FileOutputStream fos = new FileOutputStream(filepath);
                fos.write(TextPreview.getText().getBytes());
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        else if (filepath.isEmpty()) {
            fileChooser.setFileFilter(new FileNameExtensionFilter(
                    "Chỉ chọn file có đuôi (*.dat)", "dat"));
            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                filepath = fileChooser.getSelectedFile().getAbsolutePath();
                if (!filepath.endsWith(".dat"))
                    filepath = filepath.strip() + ".dat";
                try (FileOutputStream outputStream = new FileOutputStream(filepath)) {
                    outputStream.write(encodeTxt(TextPreview.getText()).getBytes());
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        }
    }//GEN-LAST:event_Save_FileActionPerformed

    private void RedChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedChooseActionPerformed
        footerPanel.setBackground(Color.red);
    }//GEN-LAST:event_RedChooseActionPerformed

    private void GreenChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenChooseActionPerformed
        footerPanel.setBackground(Color.green);
    }//GEN-LAST:event_GreenChooseActionPerformed

    private void BlueChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueChooseActionPerformed
        footerPanel.setBackground(Color.blue);
    }//GEN-LAST:event_BlueChooseActionPerformed

    private void TextPreviewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPreviewKeyPressed
        isUpdateFile = true;
    }//GEN-LAST:event_TextPreviewKeyPressed

    private void exitAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitAppBtnActionPerformed

    private void ColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorChooserActionPerformed
        JColorChooser ColorChooser = new JColorChooser();
        Color colorReturn = JColorChooser.showDialog(
                this, "Vui lòng chọn màu", Color.white);
        footerPanel.setBackground(colorReturn);
    }//GEN-LAST:event_ColorChooserActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        String strAbout = """
        Tạo File, Sửa File
        Người phát triển: Nguyễn Tấn Hoàng Nguyên
        EDUCATION: FPT Polyschool
        """;
        JOptionPane.showMessageDialog(this,
                strAbout, "Giới thiệu ứng dụng", 1);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private String encodeTxt(String s) {
        return Base64.getEncoder().encodeToString(s.getBytes());
    }

    private String decodeBase64 (String base64) {
        return new String(Base64.getDecoder().decode(base64));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem BlueChoose;
    private javax.swing.JMenuItem ColorChooser;
    private javax.swing.JRadioButtonMenuItem GreenChoose;
    private javax.swing.JMenuItem New_file;
    private javax.swing.JMenuItem Open_file;
    private javax.swing.JRadioButtonMenuItem RedChoose;
    private javax.swing.JMenuItem Save_File;
    private javax.swing.JTextArea TextPreview;
    private javax.swing.JButton aboutBtn;
    private javax.swing.ButtonGroup colorGroup;
    private javax.swing.JButton exitAPp;
    private javax.swing.JMenuItem exitAppBtn;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.ButtonGroup toolbarGroupbtn;
    // End of variables declaration//GEN-END:variables
}
